from sqlmodel import Session
from services.analysis_service import extract_clauses, flag_risks, generate_summary
from db.crud import get_document_by_id, get_queries_by_session
from fastapi import HTTPException
import json
from datetime import datetime

EXPORT_HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body {{ font-family: Arial, sans-serif; padding: 40px; color: #222; }}
  h1 {{ color: #1a365d; border-bottom: 2px solid #2563EB; padding-bottom: 8px; }}
  h2 {{ color: #2563EB; margin-top: 30px; }}
  h3 {{ color: #374151; }}
  .badge {{ display: inline-block; padding: 2px 10px; border-radius: 12px; font-size: 12px; font-weight: bold; }}
  .high {{ background: #fee2e2; color: #991b1b; }}
  .medium {{ background: #fef3c7; color: #92400e; }}
  .low {{ background: #d1fae5; color: #065f46; }}
  .critical {{ background: #fee2e2; color: #991b1b; }}
  .important {{ background: #fef3c7; color: #92400e; }}
  .standard {{ background: #f3f4f6; color: #374151; }}
  .clause-card {{ border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; margin: 10px 0; }}
  .risk-card {{ border-left: 4px solid; padding: 12px 16px; margin: 10px 0; background: #f9fafb; }}
  .risk-high {{ border-color: #ef4444; }}
  .risk-medium {{ border-color: #f59e0b; }}
  .risk-low {{ border-color: #10b981; }}
  blockquote {{ background: #f3f4f6; border-left: 4px solid #2563EB; margin: 8px 0; padding: 8px 16px; font-style: italic; }}
  .qa-item {{ background: #f9fafb; border-radius: 8px; padding: 16px; margin: 10px 0; }}
  .question {{ font-weight: bold; color: #1a365d; }}
  footer {{ margin-top: 40px; padding-top: 16px; border-top: 1px solid #e5e7eb; color: #6b7280; font-size: 12px; }}
</style>
</head>
<body>
<h1>Legal Document Analysis Report</h1>
<p><strong>Document:</strong> {filename}</p>
<p><strong>Generated:</strong> {generated_at}</p>
<p><strong>Document ID:</strong> {doc_id}</p>

<h2>Executive Summary</h2>
{summary_section}

<h2>Extracted Clauses ({clause_count} total)</h2>
{clauses_section}

<h2>Risk Analysis (Overall Risk: {overall_risk})</h2>
{risks_section}

<h2>Q&A History</h2>
{qa_section}

<footer>Generated by Legal Document Analyzer &bull; {generated_at}</footer>
</body>
</html>
"""


async def export_to_pdf(doc_id: str, session_id: str, db: Session) -> bytes:
    record = get_document_by_id(db, doc_id)
    if not record:
        raise HTTPException(404, "Document not found")

    clauses_result = await extract_clauses(doc_id, db)
    risks_result = await flag_risks(doc_id, db)
    summary_result = await generate_summary(doc_id, db)
    queries = get_queries_by_session(db, session_id)
    doc_queries = [q for q in queries if doc_id in json.loads(q.doc_ids_json)]

    # Build summary section
    summary = summary_result.get("summary", {})
    summary_html = f"<p>{summary.get('overall_summary', 'No summary available.')}</p>"
    if isinstance(summary, dict):
        if summary.get("parties"):
            summary_html += f"<p><strong>Parties:</strong> {', '.join(summary['parties'])}</p>"
        if summary.get("governing_law"):
            summary_html += f"<p><strong>Governing Law:</strong> {summary['governing_law']}</p>"

    # Build clauses section
    clauses_html = ""
    for c in clauses_result.clauses:
        clauses_html += f"""
        <div class="clause-card">
          <span class="badge {c.importance}">{c.importance.upper()}</span>
          <strong> {c.title}</strong> <em>({c.clause_type})</em><br>
          <p>{c.content}</p>
          <small>Page: {c.page_reference}</small>
        </div>"""

    # Build risks section
    risks_html = ""
    for r in risks_result.risk_flags:
        risks_html += f"""
        <div class="risk-card risk-{r.risk_level}">
          <span class="badge {r.risk_level}">{r.risk_level.upper()}</span>
          <strong> {r.risk_category}</strong><br>
          <p>{r.description}</p>
          <blockquote>{r.citation}</blockquote>
          <p><em>Recommendation: {r.recommendation}</em></p>
        </div>"""

    # Build Q&A section
    qa_html = ""
    for q in doc_queries:
        qa_html += f"""
        <div class="qa-item">
          <p class="question">Q: {q.question}</p>
          <p>A: {q.answer}</p>
        </div>"""
    if not qa_html:
        qa_html = "<p>No questions asked for this document.</p>"

    html = EXPORT_HTML_TEMPLATE.format(
        filename=record.filename,
        doc_id=doc_id,
        generated_at=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
        summary_section=summary_html,
        clause_count=clauses_result.total_count,
        clauses_section=clauses_html,
        overall_risk=risks_result.overall_risk.upper(),
        risks_section=risks_html,
        qa_section=qa_html
    )

    from weasyprint import HTML as WeasyHTML
    return WeasyHTML(string=html).write_pdf()
